version: "3.8"

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=1234
      - DB_NAME=postgres
      - AWS_REGION=eu-north-1
      - S3_BUCKET=gobucketfile
      - REDIS_ADDR=redis:6379
      - REDIS_PASSWORD=1234
      - JWT_SECRET=magic_pawns
      - AWS_ACCESS_KEY_ID=AKIAUW4RATRC4GNOIQOI
      - AWS_SECRET_ACCESS_KEY=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
    volumes:
      - C:\Users\yash chawla\.aws:/root/.aws:ro
    depends_on:
      - redis
      - db

  redis:
    image: redis:alpine
    command: redis-server --requirepass 1234
    ports:
      - "6379:6379"

  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
